### ISSUE TITLE
v3.3.0 Release Checklist

### ISSUE THREAD

**Issue by nightlark** [GMLC-TDC/HELICS#2437]
- [x] Check that all expected release assets were compiled for all platforms, the `*-source.tar.gz` file, and the `*-SHA-256.txt` file; if any are missing see `Steps to manually add a missing asset to a release` below
- [x] Make sure https://github.com/GMLC-TDC/helics-packaging/blob/main/HELICS_VERSION has been updated with the new version number; if it hasn't, manually update it (and double check that all release assets were successfully compiled)

- [x] Update the helics-apps PyPI package by [creating a new release](https://github.com/GMLC-TDC/helics-packaging/releases/new) with the **v3.3.0** tag, and description/title similar to previous releases
  - [x] Verify that the [Build Python Packages workflow](https://github.com/GMLC-TDC/helics-packaging/actions/workflows/pythonpackage.yml) for the release (not tag) runs to completion
  - [x] Verify the files uploaded to PyPI at https://pypi.org/project/helics-apps/#files include wheel files for win32, win_amd64, macosx, and manylinux
- [x] Run the [Update HELICS Packages workflow](https://github.com/GMLC-TDC/helics-packaging/actions/workflows/update-helics.yml)
  - [x] Verify that a PR was opened at https://github.com/spack/spack/pulls that looks okay and leave a review approving it. If the workflow failed or the package PR has CI errors, debug and fix
  - [x] Verify that a PR was opened at https://github.com/msys2/MINGW-packages/pulls that looks okay and leave a review approving it. If the workflow failed or the package PR has CI build errors, debug and fix
  - [x] Verify [pyhelics](https://github.com/GMLC-TDC/pyhelics) has been updated to include new/removed features, then [create a new release](https://github.com/GMLC-TDC/pyhelics/releases/new) with a matching version tag, and link to a changelog showing the difference between the two versions
  - [x] Regenerate the [matHELICS](https://github.com/GMLC-TDC/matHELICS) bindings using the C header file from HELICS, then make a release/tag a version
- [x] Run [helics-ns3 CI tests](https://github.com/GMLC-TDC/helics-ns3/actions/workflows/ci.yml) and fix any issues
- [x] Run [Test HELICS Install Action](https://github.com/GMLC-TDC/helics-action/actions/workflows/test-helics-install.yml) with both binary and source options selected; fix any issues

---

If part of the [Update HELICS Packages workflow](https://github.com/GMLC-TDC/helics-packaging/actions/workflows/update-helics.yml) fails, the failing part can be re-run on its own:

- [Spack Package Update workflow](https://github.com/GMLC-TDC/helics-packaging/actions/workflows/update-spack-package.yml)
- [MINGW Package Update workflow](https://github.com/GMLC-TDC/helics-packaging/actions/workflows/update-mingw-package.yml)
- [pyhelics Update HELICS Version workflow](https://github.com/GMLC-TDC/pyhelics/actions/workflows/update-helics.yml)
- [matHELICS Update HELICS Version workflow](https://github.com/GMLC-TDC/matHELICS/actions/workflows/update-helics.yml)

---

Steps to manually add a missing asset to a release:
1. If it was a temporary issue such as a resource being unavailable, manually trigger the [release build workflow](https://github.com/GMLC-TDC/HELICS/actions/workflows/release-build.yml) **using the workflow from `Tag: v3.3.0`**.
2. If it was a more major issue, create a branch based on the tagged release and modify the workflow and scripts in the .github subfolder as needed to make it build. Manually trigger the [release build workflow](https://github.com/GMLC-TDC/HELICS/actions/workflows/release-build.yml) **using the workflow from the branch with these fixes** and for the commit-ish field enter the release tag **v3.3.0**.
3. Download the artifact from the workflow re-run that was missing and upload it to the release.
4. Download the SHA-256.txt file for the release and add an entry for the new asset (run the `sha256sum` command on Linux to get the line to add). Replace the old SHA-256.txt file for the release with the updated version.

**Comment by nightlark** [comment]
All release tasks for v3.3.0 release have been finished.
